### ISSUE TITLE
Support for datapack advancements

### ISSUE THREAD

**Issue by OrangeUtan** [mcbeet/beet#99]
Datapack advancements are a convention from the [Minecraft Datapacks](https://discord.gg/SnJQcfq) Discord server ([their article](https://mc-datapacks.github.io/en/conventions/datapack_advancement.html) about the issue). The aim is to replace installation messages in an easily viewable and non-obstructive way by putting them on a single advancement page.

The convention is by no means standardized, but a couple of people are already using it (myself included) and I think adding built-in support would be a helpfull feature. Wether this feature can be implemented as is or should be altered is open to discussion.

## Configuration
An example configuration:
```yaml
name: Apple
description: An example datapack
author: Oran9eUtan
pipeline:
  - beet.contrib.datapack_advancement
meta:
  datapack_advancement:
    author_namespace: Oran9eUtan
    author_skull_owner: oran9eutan
    icon:
        item: "minecraft:apple"
        nbt: "{...}"
```

I'm still unsure how to exactly configure the datapack namespace, since other plugins could benefit from it. For now I put it in the datapack advancement config, but making it a top-level setting would be possible as well

### Root advancement:
![](https://mc-datapacks.github.io/en/conventions/advancement/root.png)

Path: `global:root`
```json
{
    "display": {
        "title": "Installed Datapacks",
        "description": "",
        "icon": {
            "item": "minecraft:knowledge_book"
        },
        "background": "minecraft:textures/block/gray_concrete.png",
        "show_toast": false,
        "announce_to_chat": false
    },
    "criteria": {
        "trigger": {
            "trigger": "minecraft:tick"
        }
    }
}
```

### Author namespace advancement:
![](https://mc-datapacks.github.io/en/conventions/advancement/namespace.png)

Requires:
- `author`: Name of author
- `author_namespace`: Unique namespace for author (e.g. `oran9eutan`)
- `author_skull_owner`: Skull owner of author

Path: `global:<author_namespace>`
```json
{
    "display": {
        "title": "<author>",
        "description": "",
        "icon": {
            "item": "minecraft:player_head",
            "nbt": "{SkullOwner: '<author_skull_owner>'}"
        },
        "show_toast": false,
        "announce_to_chat": false
    },
    "parent": "global:root",
    "criteria": {
        "trigger": {
            "trigger": "minecraft:tick"
        }
    }
}
```

### Project / Datapack advancement
![](https://mc-datapacks.github.io/en/conventions/advancement/datapack.png)

Requires:
- `project_name`: Name of the project
- `project_description`: Description of the project
- `icon`: The icon of the project. A json object
- `author_namespace`

```json
{
    "display": {
        "title": "<project_name>",
        "description": "<project_description>",
        "icon": <icon>,
        "announce_to_chat": false,
        "show_toast": false
    },
    "parent": "global:<author_namespace>",
    "criteria": {
        "trigger": {
            "trigger": "minecraft:tick"
        }
    }
}
```
This advancement can be put anywhere. Different user may want different locations, but a default location could be decided uppon.
There is the issue of namespace clashes, so I prefer `<author_namespace>:<project_namespace>/installed`. (e.g. `oran9eutan:apple/installed`)

**Comment by vberlier** [comment]
I wasn't familiar with this but it looks like it would fit pretty nicely in `beet.contrib`. Should be pretty easy to implement too.

**Comment by OrangeUtan** [comment]
I already implemented this with a custom plugin in another project using jinja templates ([here](https://github.com/OrangeUtan/Hats/blob/main/hats/plugins/datapack_advancement.py)). 
My only concern is the exact placement of the project advancement and the configuration of the namespaces.

I can create a pull-request and we can work it out from there

**Comment by vberlier** [comment]
By the way I looked through the implementation in your "hats" project and I have a few tips! In general, you shouldn't need to create a jinja environment manually. You can add "hats/templates" to the  "templates" option in the config file and simply do `ctx.template.render(...)`. Another option is to create a `__init__.py` file in the templates directory and use `ctx.template.add_package("hats")` to load the templates under the "hats/" prefix.

Also the built-in template manager configures proper caching for jinja bytecode and in general rendering templates is very fast. So using the cache to avoid re-generating files isn't going to make that much of a difference. Also it seems like I need to clarify the purpose of the `get_path()` method. It's meant to be used when you need to store a file or a directory that's associated with a dynamic key that is not directly usable as a filename (with slashes or special characters). In your case since the cached data pack would be static you can use an explicit path `ctx.directory / "installation_advancement_data_pack"`.

Another thing is that `Advancement` and `DataPack` are re-exported at top-level, so this can simplify imports. VSCode 
 is kind of annoying though, it doesn't pick the shortest path when it adds imports automatically.

**Comment by OrangeUtan** [comment]
Wow, thx for the many tips. I still have a rather shallow understanding of some of the features, as I'm often learning from the built-in plugins and examples without digging too deep into the core source code. Also I discover new features faster than I can master the old ones :D.

But learning is a steady process of improvement :D
